/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DragonsRouteImport } from './routes/dragons'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as RealmRealmIdRouteImport } from './routes/realm.$realmId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DragonsRoute = DragonsRouteImport.update({
  id: '/dragons',
  path: '/dragons',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const RealmRealmIdRoute = RealmRealmIdRouteImport.update({
  id: '/realm/$realmId',
  path: '/realm/$realmId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dragons': typeof DragonsRoute
  '/portal': typeof PortalRoute
  '/realm/$realmId': typeof RealmRealmIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dragons': typeof DragonsRoute
  '/portal': typeof PortalRoute
  '/realm/$realmId': typeof RealmRealmIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dragons': typeof DragonsRoute
  '/portal': typeof PortalRoute
  '/realm/$realmId': typeof RealmRealmIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dragons' | '/portal' | '/realm/$realmId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dragons' | '/portal' | '/realm/$realmId'
  id: '__root__' | '/' | '/dragons' | '/portal' | '/realm/$realmId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DragonsRoute: typeof DragonsRoute
  PortalRoute: typeof PortalRoute
  RealmRealmIdRoute: typeof RealmRealmIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dragons': {
      id: '/dragons'
      path: '/dragons'
      fullPath: '/dragons'
      preLoaderRoute: typeof DragonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realm/$realmId': {
      id: '/realm/$realmId'
      path: '/realm/$realmId'
      fullPath: '/realm/$realmId'
      preLoaderRoute: typeof RealmRealmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DragonsRoute: DragonsRoute,
  PortalRoute: PortalRoute,
  RealmRealmIdRoute: RealmRealmIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
